import { test, expect, type APIRequestContext, type Locator, type Page } from '@playwright/test';
import { cleanupDatabase } from '../helpers/db-cleanup';

type TicketResponse = {
  id: number;
  title: string;
  stage: string;
  updatedAt: string;
};

const BASE_URL = 'http://localhost:3000';

async function createTicket(request: APIRequestContext, data: Record<string, unknown>): Promise<TicketResponse> {
  const payload = { ...data } as Record<string, unknown>;

  if (typeof payload.description !== 'string') {
    payload.description = 'Generated by Playwright test';
  }

  const response = await request.post(`${BASE_URL}/api/projects/1/tickets`, { data: payload });
  expect(response.ok()).toBeTruthy();
  const ticket = (await response.json()) as Partial<TicketResponse>;

  if (typeof ticket.id !== 'number' || typeof ticket.title !== 'string' || typeof ticket.updatedAt !== 'string') {
    throw new Error('Ticket creation response missing required fields');
  }

  return ticket as TicketResponse;
}

async function getText(locator: Locator): Promise<string> {
  return (await locator.textContent()) ?? '';
}

async function getStyleValue(locator: Locator, property: string): Promise<string> {
  return locator.evaluate(
    (element, prop) => window.getComputedStyle(element).getPropertyValue(prop as string),
    property
  );
}

function getTicketCardByTitle(page: Page, title: string) {
  return page
    .locator('[data-testid="ticket-card"][data-draggable="true"]').or(page.locator('[data-testid="ticket-card"]'))
    .filter({ hasText: title })
    .first();
}

test.describe('Ticket Card Display', () => {
  test.beforeEach(async ({ request }) => {
    // Clean database before each test
    await cleanupDatabase();

    await createTicket(request, {
      title: 'Test Ticket for Card Display',
      description: 'This ticket is used for card display testing',
    });
  });

  test('should display ticket title on card', async ({ page, request }) => {
    const ticketData = {
      title: 'Display Title Test Ticket',
      description: 'Testing title display',
    };

    const createdTicket = await createTicket(request, ticketData);

    await page.goto(`${BASE_URL}/projects/1/board`);

    const ticketCard = page.locator(`[data-testid="ticket-${createdTicket.id}"]`).or(
      page.locator(`text="${ticketData.title}"`).first()
    );

    await expect(ticketCard).toBeVisible();
    expect(await getText(ticketCard)).toContain(ticketData.title);
  });

  test('should display ticket ID in format #N', async ({ page, request }) => {
    const createdTicket = await createTicket(request, {
      title: 'ID Format Test Ticket',
      description: 'Testing ID display',
    });

    await page.goto(`${BASE_URL}/projects/1/board`);

    const ticketCard = getTicketCardByTitle(page, 'ID Format Test Ticket');

    await expect(ticketCard).toBeVisible();

    const idLocator = ticketCard.locator(`text="#${createdTicket.id}"`).first();
    await expect(idLocator).toBeVisible();
  });

  test('should display status badge showing stage', async ({ page, request }) => {
    await createTicket(request, {
      title: 'Badge Test Ticket',
      description: 'Testing badge display',
    });

    await page.goto(`${BASE_URL}/projects/1/board`);

    const ticketCard = getTicketCardByTitle(page, 'Badge Test Ticket');
    await expect(ticketCard).toBeVisible();

    const badge = ticketCard.locator('text=SONNET').first();
    await expect(badge).toBeVisible();
  });

  test('should display metadata section for ticket analytics', async ({ page, request }) => {
    await createTicket(request, {
      title: 'Metadata Test Ticket',
      description: 'Testing metadata section visibility',
    });

    await page.goto(`${BASE_URL}/projects/1/board`);

    const ticketCard = getTicketCardByTitle(page, 'Metadata Test Ticket');
    await expect(ticketCard).toBeVisible();

    const metadataLabel = ticketCard.locator('text=/MESSAGES\/TOOLS PER AGENT/i').first();
    await expect(metadataLabel).toBeVisible();
  });

  test('should show visual feedback on hover', async ({ page, request }) => {
    await createTicket(request, {
      title: 'Hover Test Ticket',
      description: 'Testing hover effect',
    });

    await page.goto(`${BASE_URL}/projects/1/board`);

    const ticketCard = getTicketCardByTitle(page, 'Hover Test Ticket');
    await expect(ticketCard).toBeVisible();

    const cardSurface = ticketCard.locator('[role="article"]').first();
    const initialBg = await getStyleValue(cardSurface, 'background-color');

    await cardSurface.hover();

    await page.waitForTimeout(150);

    const hoverBg = await getStyleValue(cardSurface, 'background-color');
    expect(hoverBg).not.toBe(initialBg);
  });

  test('should expose draggable affordance on card wrapper', async ({ page, request }) => {
    await createTicket(request, {
      title: 'Click Test Ticket',
      description: 'Testing click effect',
    });

    await page.goto(`${BASE_URL}/projects/1/board`);

    const ticketCard = getTicketCardByTitle(page, 'Click Test Ticket');
    await expect(ticketCard).toBeVisible();

    const cursorStyle = await getStyleValue(ticketCard, 'cursor');
    expect(cursorStyle).toBe('grab');

    const isDraggable = await ticketCard.getAttribute('data-draggable');
    expect(isDraggable).toBe('true');
  });

  test('should open modal on click without navigation', async ({ page, request }) => {
    await createTicket(request, {
      title: 'No Navigation Test',
      description: 'Click should not navigate',
    });

    await page.goto(`${BASE_URL}/projects/1/board`);

    const initialUrl = page.url();
    const ticketCard = page.locator('text="No Navigation Test"').first();
    await expect(ticketCard).toBeVisible();

    await ticketCard.click();
    await page.waitForTimeout(200);

    // URL should not change (no navigation)
    expect(page.url()).toBe(initialUrl);

    // Modal should now be visible (new feature: ticket detail modal)
    const modal = page.locator('[role="dialog"]');
    await expect(modal).toBeVisible();

    // Modal should display the ticket title
    await expect(modal).toContainText('No Navigation Test');
  });

  test('should display all required card elements together', async ({ page, request }) => {
    const ticketData = {
      title: 'Complete Card Test',
      description: 'Testing all card elements',
    };

    const createdTicket = await createTicket(request, ticketData);

    await page.goto(`${BASE_URL}/projects/1/board`);

    const ticketCard = getTicketCardByTitle(page, ticketData.title);
    await expect(ticketCard).toBeVisible();

    const cardSurface = ticketCard.locator('[role="article"]').first();
    const hasTitle = await cardSurface.locator(`text="${ticketData.title}"`).isVisible();
    const hasId = await cardSurface.locator(`text="#${createdTicket.id}"`).isVisible();
    const hasBadge = await cardSurface.locator('text=SONNET').isVisible();

    expect(hasTitle).toBe(true);
    expect(hasId).toBe(true);
    expect(hasBadge).toBe(true);
  });

  test('should NOT display description on card', async ({ page, request }) => {
    const ticketData = {
      title: 'Description Hidden Test',
      description: 'Secret description should stay hidden from the card surface',
    };

    await createTicket(request, ticketData);

    await page.goto(`${BASE_URL}/projects/1/board`);

    const ticketCard = getTicketCardByTitle(page, ticketData.title);
    await expect(ticketCard).toBeVisible();

    const cardText = await getText(ticketCard);
    expect(cardText).not.toContain('Secret description should stay hidden from the card surface');
  });

  test('should maintain consistent card height', async ({ page, request }) => {
    const tickets = [
      { title: 'Short', description: 'Short title ticket' },
      { title: 'Medium length title for testing', description: 'Medium title' },
      {
        title: 'Very long title that might span multiple lines depending on card width and font size',
        description: 'Long title',
      },
    ];

    await Promise.all(tickets.map((ticket) => createTicket(request, ticket)));

    await page.goto(`${BASE_URL}/projects/1/board`);

    const cards = await page.locator('[data-testid^="ticket-"]').or(page.locator('.ticket-card, [class*="ticket"]')).all();

    if (cards.length >= 2) {
      const heights = await Promise.all(cards.map((card) => card.evaluate((el) => el.getBoundingClientRect().height)));

      const maxHeight = Math.max(...heights);
      const minHeight = Math.min(...heights);
      const variance = (maxHeight - minHeight) / maxHeight;

      expect(variance).toBeLessThan(0.3);
    }
  });
});
