import { test, expect } from '@playwright/test';
import { cleanupDatabase, getPrismaClient } from '../helpers/db-cleanup';
import { Stage, JobStatus, WorkflowType } from '@prisma/client';

/**
 * Contract Tests: GET /api/projects/[projectId]/tickets/[id]/tasks
 * Feature: 035-view-plan-and (User Story 2)
 * Source: specs/035-view-plan-and/contracts/api.ts
 *
 * Tests validate:
 * - Response schema (content, metadata)
 * - Error codes (400, 403, 404, 429, 500)
 * - Branch selection logic (SHIP → main, else → feature branch)
 * - Workflow type validation (FULL workflow only)
 * - Job completion validation (plan job must be COMPLETED - tasks.md generated with plan.md)
 */

test.describe('GET /api/projects/[projectId]/tickets/[id]/tasks - Success Cases', () => {
  const BASE_URL = 'http://localhost:3000';
  const prisma = getPrismaClient();

  test.beforeEach(async () => {
    await cleanupDatabase();
  });

  test.afterAll(async () => {
    await prisma.$disconnect();
  });

  /**
   * Helper: Create test ticket with branch and job
   */
  const createTestTicket = async (params: {
    stage: Stage;
    branch: string;
    workflowType: WorkflowType;
    jobStatus: JobStatus;
  }) => {
    const ticket = await prisma.ticket.create({
      data: {
        title: '[e2e] Tasks API Test',
        description: 'Test ticket for tasks endpoint',
        stage: params.stage,
        branch: params.branch,
        workflowType: params.workflowType,
        projectId: 1,
        updatedAt: new Date(),
      },
    });

    // Tasks.md is generated by plan job (same job that creates plan.md)
    await prisma.job.create({
      data: {
        ticketId: ticket.id,
        projectId: 1,
        command: 'plan',
        status: params.jobStatus,
        completedAt: params.jobStatus === 'COMPLETED' ? new Date() : null,
        updatedAt: new Date(),
      },
    });

    return ticket;
  };

  /**
   * T001: GET tasks returns valid response schema for BUILD stage ticket
   */
  test('GET tasks returns valid schema for BUILD stage ticket with feature branch', async ({
    request,
  }) => {
    const ticket = await createTestTicket({
      stage: 'BUILD',
      branch: '035-test-branch',
      workflowType: 'FULL',
      jobStatus: 'COMPLETED',
    });

    const response = await request.get(
      `${BASE_URL}/api/projects/1/tickets/${ticket.id}/tasks`
    );

    // Assert 200 OK
    expect(response.status()).toBe(200);

    // Assert response schema
    const data = await response.json();
    expect(data).toHaveProperty('content');
    expect(data).toHaveProperty('metadata');

    // Assert metadata structure
    expect(data.metadata).toHaveProperty('ticketId', ticket.id);
    expect(data.metadata).toHaveProperty('branch', '035-test-branch');
    expect(data.metadata).toHaveProperty('projectId', 1);
    expect(data.metadata).toHaveProperty('docType', 'tasks');
    expect(data.metadata).toHaveProperty('fileName', 'tasks.md');
    expect(data.metadata).toHaveProperty('filePath', 'specs/035-test-branch/tasks.md');
    expect(data.metadata).toHaveProperty('fetchedAt');

    // Assert content is string
    expect(typeof data.content).toBe('string');
  });

  /**
   * T002: GET tasks for VERIFY stage ticket uses feature branch
   */
  test('GET tasks for VERIFY stage ticket uses feature branch', async ({ request }) => {
    const ticket = await createTestTicket({
      stage: 'VERIFY',
      branch: '035-verify-branch',
      workflowType: 'FULL',
      jobStatus: 'COMPLETED',
    });

    const response = await request.get(
      `${BASE_URL}/api/projects/1/tickets/${ticket.id}/tasks`
    );

    expect(response.status()).toBe(200);

    const data = await response.json();
    expect(data.metadata.branch).toBe('035-verify-branch');
    expect(data.metadata.filePath).toBe('specs/035-verify-branch/tasks.md');
  });

  /**
   * T003: GET tasks for SHIP stage ticket uses main branch (branch selection logic)
   */
  test('GET tasks for SHIP stage ticket uses main branch', async ({ request }) => {
    const ticket = await createTestTicket({
      stage: 'SHIP',
      branch: '035-shipped-branch',
      workflowType: 'FULL',
      jobStatus: 'COMPLETED',
    });

    const response = await request.get(
      `${BASE_URL}/api/projects/1/tickets/${ticket.id}/tasks`
    );

    expect(response.status()).toBe(200);

    const data = await response.json();
    // CRITICAL: Branch selection logic - SHIP stage should use 'main'
    expect(data.metadata.branch).toBe('main');
    expect(data.metadata.filePath).toBe('specs/035-shipped-branch/tasks.md');
  });

  /**
   * T004: GET tasks for PLAN stage ticket also works (tasks.md created with plan.md)
   */
  test('GET tasks for PLAN stage ticket uses feature branch', async ({ request }) => {
    const ticket = await createTestTicket({
      stage: 'PLAN',
      branch: '035-plan-branch',
      workflowType: 'FULL',
      jobStatus: 'COMPLETED',
    });

    const response = await request.get(
      `${BASE_URL}/api/projects/1/tickets/${ticket.id}/tasks`
    );

    expect(response.status()).toBe(200);

    const data = await response.json();
    expect(data.metadata.branch).toBe('035-plan-branch');
  });
});

test.describe('GET /api/projects/[projectId]/tickets/[id]/tasks - Validation Errors', () => {
  const BASE_URL = 'http://localhost:3000';
  const prisma = getPrismaClient();

  test.beforeEach(async () => {
    await cleanupDatabase();
  });

  test.afterAll(async () => {
    await prisma.$disconnect();
  });

  /**
   * T005: GET tasks with invalid project ID returns 400
   */
  test('GET tasks with invalid project ID returns 400', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/projects/invalid/tickets/1/tasks`);

    expect(response.status()).toBe(400);

    const error = await response.json();
    expect(error.error).toBe('Invalid project ID');
    expect(error.code).toBe('VALIDATION_ERROR');
  });

  /**
   * T006: GET tasks with invalid ticket ID returns 400
   */
  test('GET tasks with invalid ticket ID returns 400', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/projects/1/tickets/invalid/tasks`);

    expect(response.status()).toBe(400);

    const error = await response.json();
    expect(error.error).toBe('Invalid ticket ID');
    expect(error.code).toBe('VALIDATION_ERROR');
  });
});

test.describe('GET /api/projects/[projectId]/tickets/[id]/tasks - Not Found Errors', () => {
  const BASE_URL = 'http://localhost:3000';
  const prisma = getPrismaClient();

  test.beforeEach(async () => {
    await cleanupDatabase();
  });

  test.afterAll(async () => {
    await prisma.$disconnect();
  });

  /**
   * T007: GET tasks for non-existent project returns 404
   */
  test('GET tasks for non-existent project returns 404', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/projects/99999/tickets/1/tasks`);

    expect(response.status()).toBe(404);

    const error = await response.json();
    expect(error.error).toBe('Project not found');
    expect(error.code).toBe('PROJECT_NOT_FOUND');
  });

  /**
   * T008: GET tasks for non-existent ticket returns 404
   */
  test('GET tasks for non-existent ticket returns 404', async ({ request }) => {
    const response = await request.get(`${BASE_URL}/api/projects/1/tickets/99999/tasks`);

    expect(response.status()).toBe(404);

    const error = await response.json();
    expect(error.error).toBe('Ticket not found');
    expect(error.code).toBe('TICKET_NOT_FOUND');
  });

  /**
   * T009: GET tasks for ticket with no branch returns 404
   */
  test('GET tasks for ticket with no branch returns 404', async ({ request }) => {
    const ticket = await prisma.ticket.create({
      data: {
        title: '[e2e] No Branch',
        description: 'Ticket without branch',
        stage: 'INBOX',
        branch: null,
        projectId: 1,
        updatedAt: new Date(),
      },
    });

    const response = await request.get(
      `${BASE_URL}/api/projects/1/tickets/${ticket.id}/tasks`
    );

    expect(response.status()).toBe(404);

    const error = await response.json();
    expect(error.error).toBe('Tasks not available');
    expect(error.code).toBe('BRANCH_NOT_ASSIGNED');
    expect(error.message).toContain('does not have a branch assigned');
  });

  /**
   * T010: GET tasks for ticket without completed plan job returns 404
   * (tasks.md is created by plan job, so no plan job = no tasks.md)
   */
  test('GET tasks for ticket without completed plan job returns 404', async ({
    request,
  }) => {
    const ticket = await prisma.ticket.create({
      data: {
        title: '[e2e] No Plan Job',
        description: 'Ticket without plan job',
        stage: 'BUILD',
        branch: '035-test',
        workflowType: 'FULL',
        projectId: 1,
        updatedAt: new Date(),
      },
    });

    const response = await request.get(
      `${BASE_URL}/api/projects/1/tickets/${ticket.id}/tasks`
    );

    expect(response.status()).toBe(404);

    const error = await response.json();
    expect(error.error).toBe('Tasks not available');
    expect(error.code).toBe('NOT_AVAILABLE_YET');
    expect(error.message).toContain('does not have a completed "plan" job');
  });

  /**
   * T011: GET tasks for ticket with RUNNING plan job returns 404
   */
  test('GET tasks for ticket with RUNNING plan job returns 404', async ({ request }) => {
    const ticket = await prisma.ticket.create({
      data: {
        title: '[e2e] Running Job',
        description: 'Ticket with running job',
        stage: 'PLAN',
        branch: '035-test',
        workflowType: 'FULL',
        projectId: 1,
        updatedAt: new Date(),
      },
    });

    await prisma.job.create({
      data: {
        ticketId: ticket.id,
        projectId: 1,
        command: 'plan',
        status: 'RUNNING',
        updatedAt: new Date(),
      },
    });

    const response = await request.get(
      `${BASE_URL}/api/projects/1/tickets/${ticket.id}/tasks`
    );

    expect(response.status()).toBe(404);

    const error = await response.json();
    expect(error.error).toBe('Tasks not available');
    expect(error.code).toBe('NOT_AVAILABLE_YET');
  });
});

test.describe('GET /api/projects/[projectId]/tickets/[id]/tasks - Authorization', () => {
  const BASE_URL = 'http://localhost:3000';
  const prisma = getPrismaClient();

  test.beforeEach(async () => {
    await cleanupDatabase();
  });

  test.afterAll(async () => {
    await prisma.$disconnect();
  });

  /**
   * T012: GET tasks for ticket in different project returns 403
   */
  test('GET tasks for ticket belonging to different project returns 403', async ({
    request,
  }) => {
    // Create ticket in project 2
    const ticket = await prisma.ticket.create({
      data: {
        title: '[e2e] Wrong Project',
        description: 'Ticket in project 2',
        stage: 'BUILD',
        branch: '035-test',
        projectId: 2,
        updatedAt: new Date(),
      },
    });

    await prisma.job.create({
      data: {
        ticketId: ticket.id,
        projectId: 2,
        command: 'plan',
        status: 'COMPLETED',
        completedAt: new Date(),
        updatedAt: new Date(),
      },
    });

    // Request tasks from project 1 (wrong project)
    const response = await request.get(
      `${BASE_URL}/api/projects/1/tickets/${ticket.id}/tasks`
    );

    expect(response.status()).toBe(403);

    const error = await response.json();
    expect(error.error).toBe('Forbidden');
    expect(error.code).toBe('WRONG_PROJECT');
  });
});

test.describe('GET /api/projects/[projectId]/tickets/[id]/tasks - GitHub API Errors', () => {
  const BASE_URL = 'http://localhost:3000';
  const prisma = getPrismaClient();

  test.beforeEach(async () => {
    await cleanupDatabase();
  });

  test.afterAll(async () => {
    await prisma.$disconnect();
  });

  /**
   * T013: GET tasks returns test mode content when TEST_MODE enabled
   * (validates GitHub API integration without actual API calls)
   */
  test('GET tasks returns mock content in test mode', async ({ request }) => {
    const ticket = await prisma.ticket.create({
      data: {
        title: '[e2e] Test Mode',
        description: 'Test mode validation',
        stage: 'BUILD',
        branch: '035-test',
        workflowType: 'FULL',
        projectId: 1,
        updatedAt: new Date(),
      },
    });

    await prisma.job.create({
      data: {
        ticketId: ticket.id,
        projectId: 1,
        command: 'plan',
        status: 'COMPLETED',
        completedAt: new Date(),
        updatedAt: new Date(),
      },
    });

    const response = await request.get(
      `${BASE_URL}/api/projects/1/tickets/${ticket.id}/tasks`
    );

    expect(response.status()).toBe(200);

    const data = await response.json();
    // In TEST_MODE, doc-fetcher returns mock content
    expect(data.content).toContain('This is mock content for tasks.md in test mode');
    expect(data.content).toContain('tasks');
  });
});
