import { Worker, Job } from 'bullmq';
import Redis from 'ioredis';
import { PrismaClient } from '@prisma/client';
import { exec } from 'child_process';
import { promisify } from 'util';
import { existsSync, mkdirSync, writeFileSync } from 'fs';
import path from 'path';
import dotenv from 'dotenv';

// Load environment variables
dotenv.config();

const execAsync = promisify(exec);
const prisma = new PrismaClient();

// Redis connection
const connection = new Redis(process.env.REDIS_URL || 'redis://localhost:6379', {
  maxRetriesPerRequest: null,
  enableReadyCheck: false,
});

// Workspace directory
const WORKSPACES_DIR = process.env.WORKSPACES_DIR || '/workspaces';

interface WorkflowJobData {
  ticketId: number;
  projectId: number;
  command: string;
  ticketTitle: string;
  ticketDescription: string;
  branch: string | null;
  githubOwner: string;
  githubRepo: string;
  jobId: number;
  attachments?: any[];
  specifyPayload?: string;
  clarificationPolicy?: string;
  answersJson?: string;
}

/**
 * MOCK VERSION - Simulates Claude execution for testing
 */
async function processJob(job: Job<WorkflowJobData>) {
  const { ticketId, command, githubOwner, githubRepo, branch, jobId, projectId } = job.data;

  console.log(`[Worker MOCK] Processing job ${job.id} - Command: ${command} for ticket ${ticketId}`);
  console.log(`[Worker MOCK] Debug inputs:
    ticket_id: ${ticketId}
    job_id: ${jobId}
    command: ${command}
    ticketTitle: ${job.data.ticketTitle}
    branch: ${branch || '(will be created)'}
  `);

  // Check if this is a test ticket
  const skipExecution = job.data.ticketTitle.includes('[e2e]');
  if (skipExecution) {
    console.log(`[Worker MOCK] '[e2e]' detected in ticket title; skipping execution`);
  }

  try {
    // Update Job Status - Running
    await updateJobStatus(jobId, 'RUNNING');

    if (skipExecution) {
      await updateJobStatus(jobId, 'COMPLETED');
      return { success: true, skipped: true };
    }

    // Setup workspace
    const workspace = path.join(WORKSPACES_DIR, `${githubOwner}-${githubRepo}`);
    const repoUrl = `https://github.com/${githubOwner}/${githubRepo}.git`;

    // Ensure workspace directory exists
    if (!existsSync(WORKSPACES_DIR)) {
      mkdirSync(WORKSPACES_DIR, { recursive: true });
    }

    // For MOCK: Create fake workspace if it doesn't exist
    if (!existsSync(workspace)) {
      console.log(`[Worker MOCK] Creating mock workspace at ${workspace}`);
      mkdirSync(workspace, { recursive: true });

      // Initialize git repo
      await execAsync(`cd ${workspace} && git init`);
      await execAsync(`cd ${workspace} && git remote add origin ${repoUrl}`);
    }

    // Configure Git
    await execAsync(`git config --global user.name "ai-board[bot]"`);
    await execAsync(`git config --global user.email "bot@ai-board.app"`);

    let currentBranch = branch;

    // MOCK: Simulate Claude execution based on command
    console.log(`[Worker MOCK] Simulating command: ${command}`);

    switch (command) {
      case 'specify': {
        // Mock branch creation
        currentBranch = `${ticketId}-${job.data.ticketTitle.toLowerCase().replace(/[^a-z0-9]/g, '-').slice(0, 30)}`;
        console.log(`[Worker MOCK] Creating mock branch: ${currentBranch}`);

        try {
          await execAsync(`cd ${workspace} && git checkout -b ${currentBranch}`);
        } catch (e) {
          // Branch might already exist
          await execAsync(`cd ${workspace} && git checkout ${currentBranch}`);
        }

        // Create mock spec file
        const specDir = path.join(workspace, 'specs', currentBranch);
        mkdirSync(specDir, { recursive: true });

        const specContent = `# Specification: ${job.data.ticketTitle}

**Ticket ID**: ${ticketId}
**Created**: ${new Date().toISOString()}

## Description
${job.data.ticketDescription}

## Mock Specification
This is a mock specification created by the test worker.

## Implementation Plan
1. Analyze requirements
2. Design solution
3. Implement feature
4. Test implementation
5. Deploy

---
*Generated by AI Board Worker (MOCK MODE)*`;

        writeFileSync(path.join(specDir, 'spec.md'), specContent);
        console.log(`[Worker MOCK] Created mock spec.md`);

        // Commit changes
        await execAsync(`cd ${workspace} && git add .`);
        await execAsync(`cd ${workspace} && git commit -m "specify: Ticket #${ticketId}" || true`);

        break;
      }

      case 'plan': {
        // Create mock plan file
        const planContent = `# Implementation Plan

## Overview
Mock implementation plan for ticket #${ticketId}

## Tasks
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

*Generated by AI Board Worker (MOCK MODE)*`;

        const specDir = path.join(workspace, 'specs', branch || 'main');
        mkdirSync(specDir, { recursive: true });
        writeFileSync(path.join(specDir, 'plan.md'), planContent);

        await execAsync(`cd ${workspace} && git add .`);
        await execAsync(`cd ${workspace} && git commit -m "plan: Ticket #${ticketId}" || true`);
        break;
      }

      case 'implement': {
        // Create mock implementation
        const implContent = `// Mock implementation for ticket #${ticketId}
console.log("Implementation placeholder");

// This would be real code in production
export function mockFeature() {
  return "Feature implemented!";
}`;

        writeFileSync(path.join(workspace, `feature-${ticketId}.js`), implContent);

        await execAsync(`cd ${workspace} && git add .`);
        await execAsync(`cd ${workspace} && git commit -m "implement: Ticket #${ticketId}" || true`);
        break;
      }

      case 'quick-impl': {
        // Mock quick implementation
        currentBranch = `${ticketId}-quick-fix`;

        try {
          await execAsync(`cd ${workspace} && git checkout -b ${currentBranch}`);
        } catch (e) {
          await execAsync(`cd ${workspace} && git checkout ${currentBranch}`);
        }

        const fixContent = `// Quick fix for ticket #${ticketId}
// ${job.data.ticketTitle}
console.log("Quick fix applied!");`;

        writeFileSync(path.join(workspace, `quick-fix-${ticketId}.js`), fixContent);

        await execAsync(`cd ${workspace} && git add .`);
        await execAsync(`cd ${workspace} && git commit -m "quick-impl: Ticket #${ticketId}" || true`);
        break;
      }

      default: {
        console.log(`[Worker MOCK] Command ${command} not mocked, creating placeholder`);

        const placeholderContent = `# ${command} - Ticket #${ticketId}\n\nMock execution completed.`;
        writeFileSync(path.join(workspace, `${command}-${ticketId}.md`), placeholderContent);

        await execAsync(`cd ${workspace} && git add .`);
        await execAsync(`cd ${workspace} && git commit -m "${command}: Ticket #${ticketId}" || true`);
      }
    }

    // Note: Not pushing to GitHub in mock mode
    console.log(`[Worker MOCK] Would push to branch: ${currentBranch} (skipped in mock mode)`);

    // Update ticket branch if new branch was created
    if (currentBranch && !branch && command === 'specify') {
      console.log(`[Worker MOCK] Updating ticket branch to: ${currentBranch}`);
      await updateTicketBranch(ticketId, projectId, currentBranch);
    }

    // Update Job Status - Success
    await updateJobStatus(jobId, 'COMPLETED');

    console.log(`[Worker MOCK] Job ${job.id} completed successfully`);
    return { success: true, branch: currentBranch, mock: true };

  } catch (error) {
    console.error(`[Worker MOCK] Job ${job.id} failed:`, error);
    await updateJobStatus(jobId, 'FAILED', error instanceof Error ? error.message : 'Unknown error');
    throw error;
  }
}

/**
 * Update job status via API
 */
async function updateJobStatus(jobId: number, status: string, logs?: string) {
  const apiUrl = process.env.API_URL || 'http://localhost:3000';
  const token = process.env.WORKFLOW_API_TOKEN;

  const response = await fetch(`${apiUrl}/api/jobs/${jobId}/status`, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
      ...(token && { 'Authorization': `Bearer ${token}` }),
    },
    body: JSON.stringify({ status, logs }),
  });

  if (!response.ok) {
    console.error(`[Worker MOCK] Failed to update job status: ${response.status} ${response.statusText}`);
  } else {
    console.log(`[Worker MOCK] Job ${jobId} status updated to ${status}`);
  }
}

/**
 * Update ticket branch via API
 */
async function updateTicketBranch(ticketId: number, projectId: number, branch: string) {
  const apiUrl = process.env.API_URL || 'http://localhost:3000';
  const token = process.env.WORKFLOW_API_TOKEN;

  const response = await fetch(`${apiUrl}/api/projects/${projectId}/tickets/${ticketId}/branch`, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
      ...(token && { 'Authorization': `Bearer ${token}` }),
    },
    body: JSON.stringify({ branch }),
  });

  if (!response.ok) {
    console.error(`[Worker MOCK] Failed to update ticket branch: ${response.status} ${response.statusText}`);
  } else {
    console.log(`[Worker MOCK] Ticket ${ticketId} branch updated to ${branch}`);
  }
}

// Create and start the worker
const worker = new Worker('ai-board-workflows', processJob, {
  connection,
  concurrency: parseInt(process.env.WORKER_CONCURRENCY || '1'),
  removeOnComplete: { count: 100 },
  removeOnFail: { count: 500 },
});

// Worker event listeners
worker.on('completed', (job) => {
  console.log(`[Worker MOCK] Job ${job.id} completed`);
});

worker.on('failed', (job, err) => {
  console.error(`[Worker MOCK] Job ${job?.id} failed:`, err);
});

worker.on('error', (err) => {
  console.error('[Worker MOCK] Worker error:', err);
});

// Graceful shutdown
process.on('SIGTERM', async () => {
  console.log('[Worker MOCK] SIGTERM received, closing worker...');
  await worker.close();
  await prisma.$disconnect();
  process.exit(0);
});

process.on('SIGINT', async () => {
  console.log('[Worker MOCK] SIGINT received, closing worker...');
  await worker.close();
  await prisma.$disconnect();
  process.exit(0);
});

console.log('🎭 [Worker MOCK] AI Board MOCK worker started');
console.log('⚠️  This is a MOCK version that simulates Claude execution');
console.log(`📍 Redis: ${process.env.REDIS_URL || 'redis://localhost:6379'}`);
console.log(`📍 API: ${process.env.API_URL || 'http://localhost:3000'}`);
console.log(`📍 Concurrency: ${process.env.WORKER_CONCURRENCY || '1'}`);
console.log(`📂 Workspaces: ${WORKSPACES_DIR}`);