import type { HealthScanType, HealthScanStatus } from '@prisma/client';

/** All scan types including passive (non-scannable) modules */
export type HealthModuleType = HealthScanType | 'QUALITY_GATE' | 'LAST_CLEAN';

/** Active scan types that can be triggered */
export const ACTIVE_SCAN_TYPES: HealthScanType[] = [
  'SECURITY',
  'COMPLIANCE',
  'TESTS',
  'SPEC_SYNC',
];

/** All 6 module types for display */
export const ALL_MODULE_TYPES: HealthModuleType[] = [
  'SECURITY',
  'COMPLIANCE',
  'TESTS',
  'QUALITY_GATE',
  'SPEC_SYNC',
  'LAST_CLEAN',
];

/** Module display metadata */
export interface ModuleMetadata {
  key: HealthModuleType;
  label: string;
  passive: boolean;
}

export const MODULE_METADATA: Record<HealthModuleType, ModuleMetadata> = {
  SECURITY: { key: 'SECURITY', label: 'Security', passive: false },
  COMPLIANCE: { key: 'COMPLIANCE', label: 'Compliance', passive: false },
  TESTS: { key: 'TESTS', label: 'Tests', passive: false },
  SPEC_SYNC: { key: 'SPEC_SYNC', label: 'Spec Sync', passive: false },
  QUALITY_GATE: { key: 'QUALITY_GATE', label: 'Quality Gate', passive: true },
  LAST_CLEAN: { key: 'LAST_CLEAN', label: 'Last Clean', passive: true },
};

/** Module status in the health response */
export interface HealthModuleStatus {
  score: number | null;
  label: string | null;
  lastScanDate?: string | null;
  lastCleanDate?: string | null;
  scanStatus?: string | null;
  issuesFound?: number | null;
  passive?: boolean;
  jobId?: number | null;
  summary: string;
}

/** Active scan info for polling */
export interface ActiveScanInfo {
  id: number;
  scanType: HealthScanType;
  status: HealthScanStatus;
  startedAt: string | null;
}

/** Full health response shape */
export interface HealthResponse {
  globalScore: number | null;
  label: string;
  color: { text: string; bg: string; fill: string };
  modules: {
    security: HealthModuleStatus;
    compliance: HealthModuleStatus;
    tests: HealthModuleStatus;
    specSync: HealthModuleStatus;
    qualityGate: QualityGateModuleStatus;
    lastClean: LastCleanModuleStatus;
  };
  lastFullScanDate: string | null;
  activeScans: ActiveScanInfo[];
}

/** Scan record shape for history API */
export interface ScanHistoryItem {
  id: number;
  scanType: HealthScanType;
  status: HealthScanStatus;
  score: number | null;
  issuesFound: number | null;
  issuesFixed: number | null;
  baseCommit: string | null;
  headCommit: string | null;
  durationMs: number | null;
  errorMessage: string | null;
  startedAt: string | null;
  completedAt: string | null;
  createdAt: string;
}

/** Scan history response */
export interface ScanHistoryResponse {
  scans: ScanHistoryItem[];
  nextCursor: number | null;
  hasMore: boolean;
}

/** Scan history item with optional report field */
export interface ScanHistoryItemWithReport extends ScanHistoryItem {
  report: string | null;
}

// --- Scan Report Types (discriminated union for HealthScan.report JSON) ---

/** Individual issue found by a scan */
export interface ReportIssue {
  id: string;
  severity: 'high' | 'medium' | 'low';
  description: string;
  file?: string | undefined;
  line?: number | undefined;
  category?: string | undefined;
}

/** Ticket generated by a scan */
export interface GeneratedTicket {
  ticketKey: string;
  stage: string;
}

/** Security: issues grouped by severity */
export interface SecurityReport {
  type: 'SECURITY';
  issues: ReportIssue[];
  generatedTickets: GeneratedTicket[];
}

/** Compliance: issues grouped by category (constitution principle) */
export interface ComplianceReport {
  type: 'COMPLIANCE';
  issues: ReportIssue[];
  generatedTickets: GeneratedTicket[];
}

/** Tests: split into auto-fixed and non-fixable */
export interface TestsReport {
  type: 'TESTS';
  autoFixed: ReportIssue[];
  nonFixable: ReportIssue[];
  generatedTickets: GeneratedTicket[];
}

/** Spec sync entry */
export interface SpecSyncEntry {
  specPath: string;
  status: 'synced' | 'drifted';
  drift?: string | undefined;
}

/** Spec Sync: per-spec sync status */
export interface SpecSyncReport {
  type: 'SPEC_SYNC';
  specs: SpecSyncEntry[];
  generatedTickets: GeneratedTicket[];
}

/** Quality dimension score */
export interface QualityDimension {
  name: string;
  score: number | null;
}

/** Quality ticket reference */
export interface QualityTicket {
  ticketKey: string;
  score: number | null;
}

/** Quality Gate (passive): dimension breakdown */
export interface QualityGateReport {
  type: 'QUALITY_GATE';
  dimensions: QualityDimension[];
  recentTickets: QualityTicket[];
}

/** Last Clean (passive): cleanup summary */
export interface LastCleanReport {
  type: 'LAST_CLEAN';
  filesCleaned: number;
  remainingIssues: number;
  summary: string;
}

/** Discriminated union of all report types */
export type ScanReport =
  | SecurityReport
  | ComplianceReport
  | TestsReport
  | SpecSyncReport
  | QualityGateReport
  | LastCleanReport;

// --- Quality Gate Aggregate Types (derived, not persisted) ---

export interface QualityGateTrend {
  type: 'improvement' | 'regression' | 'stable' | 'new' | 'no_data';
  currentAverage: number | null;
  previousAverage: number | null;
  delta: number | null;
}

export interface ThresholdDistribution {
  excellent: number;
  good: number;
  fair: number;
  poor: number;
}

export interface DimensionAverage {
  name: string;
  averageScore: number | null;
  weight: number;
}

export interface QualityGateTicketItem {
  ticketKey: string;
  title: string;
  score: number;
  label: string;
  completedAt: string;
}

export interface TrendDataPoint {
  week: string;
  averageScore: number;
  ticketCount: number;
}

export interface QualityGateAggregate {
  averageScore: number | null;
  ticketCount: number;
  trend: QualityGateTrend;
  distribution: ThresholdDistribution;
  dimensions: DimensionAverage[];
  recentTickets: QualityGateTicketItem[];
  trendData: TrendDataPoint[];
}

export interface QualityGateModuleStatus extends HealthModuleStatus {
  passive: true;
  ticketCount: number;
  trend: {
    type: 'improvement' | 'regression' | 'stable' | 'new' | 'no_data';
    delta: number | null;
    previousAverage: number | null;
  };
  distribution: ThresholdDistribution;
  detail: {
    dimensions: DimensionAverage[];
    recentTickets: QualityGateTicketItem[];
    trendData: TrendDataPoint[];
  } | null;
}

// --- Last Clean Aggregate Types (derived, not persisted) ---

export interface LastCleanHistoryItem {
  jobId: number;
  completedAt: string;
  filesCleaned: number;
  remainingIssues: number;
  summary: string;
  ticketKey: string | null;
}

export interface LastCleanAggregate {
  lastCleanDate: string | null;
  filesCleaned: number;
  remainingIssues: number;
  daysAgo: number | null;
  isOverdue: boolean;
  status: 'ok' | 'overdue' | 'never';
  summary: string;
  history: LastCleanHistoryItem[];
}

export interface LastCleanModuleStatus extends HealthModuleStatus {
  passive: true;
  lastCleanDate: string | null;
  jobId: number | null;
  filesCleaned: number;
  remainingIssues: number;
  daysAgo: number | null;
  isOverdue: boolean;
  status: 'ok' | 'overdue' | 'never';
  detail: {
    summary: string;
    history: LastCleanHistoryItem[];
  } | null;
}
