import { test, expect, type APIRequestContext, type Locator, type Page } from '@playwright/test';
import { cleanupDatabase } from '../../helpers/db-cleanup';

const BASE_URL = 'http://localhost:3000';

type TicketResponse = {
  id: number;
  title: string;
};

function buildTitle(length: number): string {
  const base = 'Truncation title demonstration ';
  return base.repeat(Math.ceil(length / base.length)).slice(0, length).trim();
}

async function createTicket(request: APIRequestContext, data: Record<string, unknown>): Promise<TicketResponse> {
  const payload = { ...data } as Record<string, unknown>;

  if (typeof payload.description !== 'string') {
    payload.description = 'Generated by Playwright truncation test';
  }

  const response = await request.post(`${BASE_URL}/api/projects/1/tickets`, { data: payload });
  expect(response.ok()).toBeTruthy();
  const json = (await response.json()) as Partial<TicketResponse>;
  if (typeof json.id !== 'number' || typeof json.title !== 'string') {
    throw new Error('Ticket API did not return required fields');
  }
  return json as TicketResponse;
}

function getTicketCard(page: Page, title: string) {
  return page.locator('[data-testid="ticket-card"]').filter({ hasText: title }).first();
}

function getTitleElement(card: Locator) {
  return card.locator('[role="article"] h3').first();
}

async function getStyle(locator: Locator, property: string): Promise<string> {
  return locator.evaluate((element, prop) => window.getComputedStyle(element).getPropertyValue(prop as string), property);
}

test.describe('Ticket Title Truncation', () => {
  test.beforeEach(async () => {
    // Clean database before each test
    await cleanupDatabase();
  });

  test('should truncate very long title at 2 lines', async ({ page, request }) => {
    const longTitle = buildTitle(100);

    await createTicket(request, {
      title: longTitle,
      description: 'Testing truncation',
    });

    await page.goto(`${BASE_URL}/projects/1/board`);

    const ticketCard = getTicketCard(page, longTitle);
    await expect(ticketCard).toBeVisible();

    const titleElement = getTitleElement(ticketCard);

    const lineClamp = await getStyle(titleElement, '-webkit-line-clamp');
    const overflow = await getStyle(titleElement, 'overflow');
    const textOverflow = await getStyle(titleElement, 'text-overflow');

    const hasTruncation = lineClamp === '2' || overflow === 'hidden' || textOverflow.includes('ellipsis');
    expect(hasTruncation).toBe(true);
  });

  test('should display ellipsis (...) when title is truncated', async ({ page, request }) => {
    const longTitle = buildTitle(100);

    await createTicket(request, {
      title: longTitle,
      description: 'Ellipsis test',
    });

    await page.goto(`${BASE_URL}/projects/1/board`);

    const ticketCard = page.locator('[data-testid="ticket-card"]').first();
    await expect(ticketCard).toBeVisible();

    const titleElement = getTitleElement(ticketCard);

    const classList = await titleElement.getAttribute('class');
    expect(classList ?? '').toContain('line-clamp-2');

    const overflow = await getStyle(titleElement, 'overflow');
    expect(overflow).toBe('hidden');
  });

  test('should maintain consistent heights for truncated titles', async ({ page, request }) => {
    const titles = [
      'Short title',
      buildTitle(80),
      buildTitle(100),
    ];

    await Promise.all(
      titles.map((title) =>
        createTicket(request, {
          title,
          description: 'Consistency check',
        })
      )
    );

    await page.goto(`${BASE_URL}/projects/1/board`);

    const titleElements = await page.locator('[data-testid="ticket-card"] [role="article"] h3').all();

    if (titleElements.length >= 2) {
      const heights = await Promise.all(
        titleElements.map((element) => element.evaluate((el) => el.getBoundingClientRect().height))
      );

      const maxHeight = Math.max(...heights);
      const minHeight = Math.min(...heights);
      const variance = (maxHeight - minHeight) / maxHeight;

      expect(variance).toBeLessThan(0.55);
    }
  });

  test('should keep tooltip or full title accessible', async ({ page, request }) => {
    const longTitle = buildTitle(100);

    await createTicket(request, {
      title: longTitle,
      description: 'Tooltip test',
    });

    await page.goto(`${BASE_URL}/projects/1/board`);

    const ticketCard = getTicketCard(page, longTitle);
    await expect(ticketCard).toBeVisible();

    const titleElement = getTitleElement(ticketCard);
    const titleAttr = await titleElement.getAttribute('title');
    expect(titleAttr).toBe(longTitle);
  });
});
