/**
 * Integration tests for TelemetryContextFile schema validation
 *
 * These tests verify the structure of .telemetry-context.json files
 * generated by the workflow's fetch-telemetry.sh script.
 */

import { describe, it, expect } from 'vitest';
import type { TicketTelemetry } from '@/lib/types/comparison';

/**
 * TelemetryContextFile interface
 *
 * JSON file structure written by workflow, read by compare command.
 * Location: specs/$BRANCH/.telemetry-context.json
 */
interface TelemetryContextFile {
  /** ISO timestamp of generation */
  generatedAt: string;

  /** Telemetry data keyed by ticket key */
  tickets: Record<string, TicketTelemetry>;
}

describe('TelemetryContextFile Schema', () => {
  it('should validate a complete context file structure', () => {
    const context: TelemetryContextFile = {
      generatedAt: new Date().toISOString(),
      tickets: {
        'AIB-127': {
          ticketKey: 'AIB-127',
          inputTokens: 35000,
          outputTokens: 18000,
          cacheReadTokens: 8000,
          cacheCreationTokens: 3000,
          costUsd: 0.1023,
          durationMs: 33000,
          model: 'claude-sonnet-4-5-20251101',
          toolsUsed: ['Edit', 'Read', 'Write', 'Bash'],
          jobCount: 2,
          hasData: true,
        },
      },
    };

    // Validate top-level structure
    expect(context.generatedAt).toBeDefined();
    expect(typeof context.generatedAt).toBe('string');
    expect(new Date(context.generatedAt).toISOString()).toBe(context.generatedAt);
    expect(context.tickets).toBeDefined();
    expect(typeof context.tickets).toBe('object');

    // Validate ticket telemetry structure
    const telemetry = context.tickets['AIB-127'];
    expect(telemetry.ticketKey).toBe('AIB-127');
    expect(typeof telemetry.inputTokens).toBe('number');
    expect(typeof telemetry.outputTokens).toBe('number');
    expect(typeof telemetry.cacheReadTokens).toBe('number');
    expect(typeof telemetry.cacheCreationTokens).toBe('number');
    expect(typeof telemetry.costUsd).toBe('number');
    expect(typeof telemetry.durationMs).toBe('number');
    expect(typeof telemetry.model).toBe('string');
    expect(Array.isArray(telemetry.toolsUsed)).toBe(true);
    expect(typeof telemetry.jobCount).toBe('number');
    expect(typeof telemetry.hasData).toBe('boolean');
  });

  it('should validate empty telemetry for tickets without data', () => {
    const context: TelemetryContextFile = {
      generatedAt: new Date().toISOString(),
      tickets: {
        'AIB-128': {
          ticketKey: 'AIB-128',
          inputTokens: 0,
          outputTokens: 0,
          cacheReadTokens: 0,
          cacheCreationTokens: 0,
          costUsd: 0,
          durationMs: 0,
          model: null,
          toolsUsed: [],
          jobCount: 0,
          hasData: false,
        },
      },
    };

    const telemetry = context.tickets['AIB-128'];
    expect(telemetry.hasData).toBe(false);
    expect(telemetry.costUsd).toBe(0);
    expect(telemetry.durationMs).toBe(0);
    expect(telemetry.model).toBeNull();
    expect(telemetry.toolsUsed).toEqual([]);
    expect(telemetry.jobCount).toBe(0);
  });

  it('should support multiple tickets in a single context file', () => {
    const context: TelemetryContextFile = {
      generatedAt: '2026-01-03T14:30:00.000Z',
      tickets: {
        'AIB-127': {
          ticketKey: 'AIB-127',
          inputTokens: 35000,
          outputTokens: 18000,
          cacheReadTokens: 8000,
          cacheCreationTokens: 3000,
          costUsd: 0.1023,
          durationMs: 33000,
          model: 'claude-sonnet-4-5-20251101',
          toolsUsed: ['Edit', 'Read'],
          jobCount: 2,
          hasData: true,
        },
        'AIB-128': {
          ticketKey: 'AIB-128',
          inputTokens: 0,
          outputTokens: 0,
          cacheReadTokens: 0,
          cacheCreationTokens: 0,
          costUsd: 0,
          durationMs: 0,
          model: null,
          toolsUsed: [],
          jobCount: 0,
          hasData: false,
        },
        'AIB-129': {
          ticketKey: 'AIB-129',
          inputTokens: 50000,
          outputTokens: 25000,
          cacheReadTokens: 10000,
          cacheCreationTokens: 5000,
          costUsd: 0.1456,
          durationMs: 45000,
          model: 'claude-opus-4-5-20251101',
          toolsUsed: ['Edit', 'Write', 'Bash', 'Glob', 'Grep'],
          jobCount: 3,
          hasData: true,
        },
      },
    };

    expect(Object.keys(context.tickets)).toHaveLength(3);
    expect(context.tickets['AIB-127'].hasData).toBe(true);
    expect(context.tickets['AIB-128'].hasData).toBe(false);
    expect(context.tickets['AIB-129'].hasData).toBe(true);

    // Verify cost ordering
    expect(context.tickets['AIB-129'].costUsd).toBeGreaterThan(context.tickets['AIB-127'].costUsd);
    expect(context.tickets['AIB-127'].costUsd).toBeGreaterThan(context.tickets['AIB-128'].costUsd);
  });

  it('should validate ISO timestamp format', () => {
    const validTimestamps = [
      '2026-01-03T14:30:00Z',
      '2026-01-03T14:30:00.000Z',
      '2026-01-03T14:30:00.123Z',
    ];

    for (const timestamp of validTimestamps) {
      const context: TelemetryContextFile = {
        generatedAt: timestamp,
        tickets: {},
      };

      // Should be parseable as Date
      const date = new Date(context.generatedAt);
      expect(date.toString()).not.toBe('Invalid Date');
    }
  });

  it('should correctly identify hasData based on costUsd', () => {
    // hasData should be true when costUsd > 0
    const telemetryWithCost: TicketTelemetry = {
      ticketKey: 'AIB-130',
      inputTokens: 1000,
      outputTokens: 500,
      cacheReadTokens: 0,
      cacheCreationTokens: 0,
      costUsd: 0.0001,
      durationMs: 1000,
      model: 'claude-sonnet-4-5-20251101',
      toolsUsed: [],
      jobCount: 1,
      hasData: true,
    };

    expect(telemetryWithCost.hasData).toBe(true);
    expect(telemetryWithCost.costUsd).toBeGreaterThan(0);

    // hasData should be false when costUsd is 0
    const telemetryWithoutCost: TicketTelemetry = {
      ticketKey: 'AIB-131',
      inputTokens: 0,
      outputTokens: 0,
      cacheReadTokens: 0,
      cacheCreationTokens: 0,
      costUsd: 0,
      durationMs: 0,
      model: null,
      toolsUsed: [],
      jobCount: 0,
      hasData: false,
    };

    expect(telemetryWithoutCost.hasData).toBe(false);
    expect(telemetryWithoutCost.costUsd).toBe(0);
  });
});
