import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { verifyTicketAccess } from '@/lib/db/auth-helpers';
import { listTicketComparisons } from '@/lib/comparison/comparison-detail';
import { validateWorkflowAuth } from '@/app/lib/workflow-auth';
import { persistGeneratedComparisonArtifacts } from '@/lib/comparison/comparison-generator';
import { prisma } from '@/lib/db/client';
import type { Agent, Stage, WorkflowType } from '@prisma/client';

const paramsSchema = z.object({
  projectId: z.coerce.number().int().positive(),
  id: z.coerce.number().int().positive(),
});

const querySchema = z.object({
  limit: z.coerce.number().int().positive().max(50).default(10),
});

export async function GET(
  request: NextRequest,
  context: { params: Promise<{ projectId: string; id: string }> }
): Promise<NextResponse> {
  try {
    const paramsResult = paramsSchema.safeParse(await context.params);
    if (!paramsResult.success) {
      return NextResponse.json(
        { error: 'Invalid project or ticket ID', code: 'VALIDATION_ERROR' },
        { status: 400 }
      );
    }

    const { projectId, id: ticketId } = paramsResult.data;
    const queryResult = querySchema.safeParse({
      limit: request.nextUrl.searchParams.get('limit') ?? undefined,
    });

    if (!queryResult.success) {
      return NextResponse.json(
        { error: 'Invalid query parameters', code: 'VALIDATION_ERROR' },
        { status: 400 }
      );
    }

    const ticket = await verifyTicketAccess(ticketId, request);
    if (ticket.projectId !== projectId) {
      return NextResponse.json(
        { error: 'Forbidden', code: 'WRONG_PROJECT' },
        { status: 403 }
      );
    }

    const result = await listTicketComparisons(ticketId, queryResult.data.limit);
    return NextResponse.json(result);
  } catch (error) {
    if (error instanceof Error && error.message === 'Ticket not found') {
      return NextResponse.json(
        { error: 'Ticket not found', code: 'TICKET_NOT_FOUND' },
        { status: 404 }
      );
    }

    return NextResponse.json(
      { error: 'Internal server error', code: 'INTERNAL_ERROR' },
      { status: 500 }
    );
  }
}

const ticketRefSchema = z.object({
  id: z.number().int().positive(),
  ticketKey: z.string(),
  title: z.string(),
  stage: z.enum(['INBOX', 'SPECIFY', 'PLAN', 'BUILD', 'VERIFY', 'SHIP']),
  workflowType: z.enum(['FULL', 'QUICK', 'CLEAN']),
  agent: z.enum(['CLAUDE', 'CODEX']).nullable(),
});

const implementationMetricsSchema = z.object({
  ticketKey: z.string(),
  linesAdded: z.number(),
  linesRemoved: z.number(),
  linesChanged: z.number(),
  filesChanged: z.number(),
  changedFiles: z.array(z.string()),
  testFilesChanged: z.number(),
  testCoverage: z.number().optional(),
  hasData: z.boolean(),
});

const constitutionPrincipleSchema = z.object({
  name: z.string(),
  section: z.string(),
  passed: z.boolean(),
  notes: z.string(),
});

const complianceScoreSchema = z.object({
  overall: z.number(),
  totalPrinciples: z.number(),
  passedPrinciples: z.number(),
  principles: z.array(constitutionPrincipleSchema),
});

const ticketTelemetrySchema = z.object({
  ticketKey: z.string(),
  inputTokens: z.number(),
  outputTokens: z.number(),
  cacheReadTokens: z.number(),
  cacheCreationTokens: z.number(),
  costUsd: z.number(),
  durationMs: z.number(),
  model: z.string().nullable(),
  toolsUsed: z.array(z.string()),
  jobCount: z.number(),
  hasData: z.boolean(),
});

const alignmentDimensionsSchema = z.object({
  requirements: z.number(),
  scenarios: z.number(),
  entities: z.number(),
  keywords: z.number(),
});

const comparisonDataSchema = z.object({
  sourceTicket: ticketRefSchema,
  participants: z.array(ticketRefSchema).min(1),
  branch: z.string(),
  report: z.object({
    metadata: z.object({
      generatedAt: z.string(),
      sourceTicket: z.string(),
      comparedTickets: z.array(z.string()),
      filePath: z.string(),
    }),
    summary: z.string(),
    alignment: z.object({
      overall: z.number(),
      dimensions: alignmentDimensionsSchema,
      isAligned: z.boolean(),
      matchingRequirements: z.array(z.string()),
      matchingEntities: z.array(z.string()),
    }),
    implementation: z.record(z.string(), implementationMetricsSchema),
    compliance: z.record(z.string(), complianceScoreSchema),
    telemetry: z.record(z.string(), ticketTelemetrySchema),
    recommendation: z.string(),
    warnings: z.array(z.string()),
  }),
});

/**
 * POST /api/projects/[projectId]/tickets/[id]/comparisons
 *
 * Persist comparison data generated by the /compare command.
 * Authenticated via workflow token (same as job status updates).
 */
export async function POST(
  request: NextRequest,
  context: { params: Promise<{ projectId: string; id: string }> }
): Promise<NextResponse> {
  try {
    const authResult = validateWorkflowAuth(request);
    if (!authResult.isValid) {
      return NextResponse.json(
        { error: 'Unauthorized', code: 'UNAUTHORIZED' },
        { status: 401 }
      );
    }

    const paramsResult = paramsSchema.safeParse(await context.params);
    if (!paramsResult.success) {
      return NextResponse.json(
        { error: 'Invalid project or ticket ID', code: 'VALIDATION_ERROR' },
        { status: 400 }
      );
    }

    const { projectId, id: ticketId } = paramsResult.data;

    // Verify ticket exists and belongs to project
    const ticket = await prisma.ticket.findUnique({
      where: { id: ticketId },
      select: { id: true, projectId: true },
    });

    if (!ticket) {
      return NextResponse.json(
        { error: 'Ticket not found', code: 'TICKET_NOT_FOUND' },
        { status: 404 }
      );
    }

    if (ticket.projectId !== projectId) {
      return NextResponse.json(
        { error: 'Forbidden', code: 'WRONG_PROJECT' },
        { status: 403 }
      );
    }

    let body;
    try {
      body = await request.json();
    } catch {
      return NextResponse.json(
        { error: 'Invalid JSON', code: 'VALIDATION_ERROR' },
        { status: 400 }
      );
    }

    const validationResult = comparisonDataSchema.safeParse(body);
    if (!validationResult.success) {
      return NextResponse.json(
        {
          error: 'Invalid comparison data',
          code: 'VALIDATION_ERROR',
          details: validationResult.error.issues.slice(0, 5),
        },
        { status: 400 }
      );
    }

    const data = validationResult.data;

    // Transform implementation records to match ImplementationMetrics type
    // (exactOptionalPropertyTypes requires explicit undefined removal)
    const implementation: Record<string, import('@/lib/types/comparison').ImplementationMetrics> =
      Object.fromEntries(
        Object.entries(data.report.implementation).map(([key, val]) => {
          const base: import('@/lib/types/comparison').ImplementationMetrics = {
            ticketKey: val.ticketKey,
            linesAdded: val.linesAdded,
            linesRemoved: val.linesRemoved,
            linesChanged: val.linesChanged,
            filesChanged: val.filesChanged,
            changedFiles: val.changedFiles,
            testFilesChanged: val.testFilesChanged,
            hasData: val.hasData,
          };
          if (val.testCoverage != null) {
            base.testCoverage = val.testCoverage;
          }
          return [key, base];
        })
      );

    const result = await persistGeneratedComparisonArtifacts({
      projectId,
      sourceTicket: data.sourceTicket as {
        id: number;
        ticketKey: string;
        title: string;
        stage: Stage;
        workflowType: WorkflowType;
        agent: Agent | null;
      },
      participants: data.participants as Array<{
        id: number;
        ticketKey: string;
        title: string;
        stage: Stage;
        workflowType: WorkflowType;
        agent: Agent | null;
      }>,
      branch: data.branch,
      report: {
        ...data.report,
        metadata: {
          ...data.report.metadata,
          generatedAt: new Date(data.report.metadata.generatedAt),
        },
        implementation,
      },
    });

    return NextResponse.json(
      { id: result.record.id, markdownPath: result.markdownPath },
      { status: 201 }
    );
  } catch (error) {
    console.error('[Comparison Persist] Error:', error);
    return NextResponse.json(
      { error: 'Internal server error', code: 'INTERNAL_ERROR' },
      { status: 500 }
    );
  }
}
