import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service - AI Board',
  description: 'Terms of Service for AI Board',
};

export default function TermsOfServicePage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12">
      <h1 className="mb-8 text-3xl font-bold text-white">Terms of Service</h1>
      <p className="mb-6 text-sm text-[hsl(var(--ctp-subtext-0))]">
        Last updated: March 11, 2026
      </p>

      <div className="space-y-8 text-[hsl(var(--ctp-subtext-0))]">
        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">1. Acceptance of Terms</h2>
          <p>
            By accessing or using AI Board (&quot;the Service&quot;), you agree to be bound by these
            Terms of Service. If you do not agree, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">2. Description of Service</h2>
          <p>
            AI Board is a kanban-style project management platform that integrates AI-driven
            development workflows. The Service orchestrates AI agents to generate code,
            specifications, and other artifacts on your behalf.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">3. User Accounts</h2>
          <p>
            You must authenticate via a supported third-party provider (e.g., GitHub) to use the
            Service. You are responsible for maintaining the security of your account and for all
            activities that occur under it.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">
            4. Bring Your Own Key (BYOK)
          </h2>
          <p>
            The Service may require you to provide your own API keys for third-party AI providers.
            You are solely responsible for any costs incurred through the use of your API keys,
            including but not limited to token usage, rate limits, and billing from those providers.
            AI Board does not monitor, control, or assume liability for charges on your API
            accounts.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">5. AI-Generated Content</h2>
          <p>
            Code, specifications, and other content generated by AI agents through the Service are
            provided &quot;as is.&quot; You are solely responsible for reviewing, testing, and
            deploying any AI-generated output. AI Board makes no warranties regarding the
            correctness, security, or fitness for purpose of AI-generated content.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">6. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="ml-6 mt-2 list-disc space-y-1">
            <li>Use the Service for any unlawful purpose</li>
            <li>Attempt to gain unauthorized access to the Service or its systems</li>
            <li>Interfere with or disrupt the Service</li>
            <li>Use the Service to generate malicious code or harmful content</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">
            7. Limitation of Liability
          </h2>
          <p>
            To the maximum extent permitted by law, AI Board and its operators shall not be liable
            for any indirect, incidental, special, consequential, or punitive damages, including
            but not limited to loss of profits, data, or business opportunities, arising from your
            use of the Service. This includes, without limitation, any damages resulting from
            AI-generated code, API key usage costs, or service interruptions.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">8. Intellectual Property</h2>
          <p>
            You retain ownership of any code and content you create using the Service. AI Board
            does not claim ownership of your projects, repositories, or AI-generated output
            produced on your behalf.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">9. Service Availability</h2>
          <p>
            We strive to keep the Service available but do not guarantee uninterrupted access. The
            Service may be modified, suspended, or discontinued at any time without prior notice.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">10. Changes to Terms</h2>
          <p>
            We may update these Terms from time to time. Continued use of the Service after changes
            constitutes acceptance of the updated Terms.
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-white">11. Contact</h2>
          <p>
            For questions about these Terms, please open an issue on our GitHub repository.
          </p>
        </section>
      </div>
    </div>
  );
}
